blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ â€‹Multiverse Discord Server
    url: https://discord.gg/NZtfKky
    about: Need help with using Multiverse-Core or just want to chat with the devs? Join the Multiverse Discord Server for help!
