name: 'Generic: Test'

on:
  workflow_call:
    inputs:
      plugin_name:
        description: 'Plugin name'
        required: true
        type: string

jobs:
  test-and-artifact:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run unit tests
        run: ./gradlew build
        env:
          GITHUB_VERSION: pr${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Artifact output
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.plugin_name }}-pr${{ github.event.pull_request.number }}
          path: build/libs/${{ inputs.plugin_name }}-pr${{ github.event.pull_request.number }}.jar

  comment-artifact:
    needs: test-and-artifact
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: benwoo1110/artifact-comment-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
